services:
  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    environment:
      NGINX_PROXY_PASS_URL: http://registry:5000
      REGISTRY_TITLE: nexus-prime registry
      DELETE_IMAGES: "true"
      SHOW_CONTENT_DIGEST: "true"
    expose:
      - "80"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "2"
    depends_on:
      - registry
    networks:
      - nexus
    restart: unless-stopped

networks:
  nexus:
    external: true
